-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  booking_code text NOT NULL UNIQUE,
  user_id uuid NOT NULL,
  schedule_id uuid NOT NULL,
  customer_name text NOT NULL,
  customer_email text NOT NULL,
  customer_phone text NOT NULL,
  seat_ids ARRAY NOT NULL,
  total_amount integer NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::booking_status,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  confirmed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  payment_expires_at timestamp with time zone,
  payment_timeout_minutes integer DEFAULT 15,
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT bookings_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.schedules(id)
);
CREATE TABLE public.event_registrations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  registration_code text NOT NULL UNIQUE,
  event_id uuid NOT NULL,
  user_id uuid NOT NULL,
  participant_name text NOT NULL,
  participant_email text NOT NULL,
  participant_phone text NOT NULL,
  amount integer NOT NULL,
  payment_status USER-DEFINED DEFAULT 'pending'::payment_status,
  status USER-DEFINED DEFAULT 'pending'::booking_status,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  confirmed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  CONSTRAINT event_registrations_pkey PRIMARY KEY (id),
  CONSTRAINT event_registrations_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT event_registrations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  theater_id uuid NOT NULL,
  venue_id uuid,
  type USER-DEFINED NOT NULL,
  title text NOT NULL,
  description text,
  thumbnail_url text,
  event_date timestamp with time zone NOT NULL,
  duration integer,
  max_participants integer NOT NULL,
  current_participants integer DEFAULT 0,
  price integer NOT NULL,
  instructor text,
  guide text,
  artists ARRAY,
  requirements ARRAY,
  includes ARRAY,
  tags ARRAY,
  status USER-DEFINED DEFAULT 'scheduled'::event_status,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_theater_id_fkey FOREIGN KEY (theater_id) REFERENCES public.theaters(id),
  CONSTRAINT events_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.venues(id)
);
CREATE TABLE public.floors (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  theater_id uuid NOT NULL,
  floor_number integer NOT NULL CHECK (floor_number >= '-2'::integer AND floor_number <= 20),
  name text NOT NULL,
  floor_type USER-DEFINED NOT NULL DEFAULT 'main'::floor_type,
  description text,
  total_halls integer DEFAULT 0,
  total_seats integer DEFAULT 0,
  has_elevator boolean DEFAULT false,
  has_restroom boolean DEFAULT false,
  has_bar boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  venue_id uuid,
  CONSTRAINT floors_pkey PRIMARY KEY (id),
  CONSTRAINT floors_theater_id_fkey FOREIGN KEY (theater_id) REFERENCES public.theaters(id),
  CONSTRAINT floors_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.venues(id)
);
CREATE TABLE public.halls (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  floor_id uuid NOT NULL,
  theater_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  capacity integer NOT NULL DEFAULT 0 CHECK (capacity >= 0),
  total_rows integer DEFAULT 0,
  seats_per_row integer DEFAULT 0,
  stage_width numeric,
  stage_depth numeric,
  stage_height numeric,
  has_sound_system boolean DEFAULT false,
  has_lighting_system boolean DEFAULT false,
  has_projection boolean DEFAULT false,
  has_orchestra_pit boolean DEFAULT false,
  status USER-DEFINED NOT NULL DEFAULT 'active'::hall_status,
  images ARRAY DEFAULT '{}'::text[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  has_backstage boolean DEFAULT false,
  has_dressing_room boolean DEFAULT false,
  venue_id uuid,
  CONSTRAINT halls_pkey PRIMARY KEY (id),
  CONSTRAINT halls_floor_id_fkey FOREIGN KEY (floor_id) REFERENCES public.floors(id),
  CONSTRAINT halls_theater_id_fkey FOREIGN KEY (theater_id) REFERENCES public.theaters(id),
  CONSTRAINT halls_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.venues(id)
);
CREATE TABLE public.livestream_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  livestream_id uuid NOT NULL,
  user_id uuid,
  message text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT livestream_comments_pkey PRIMARY KEY (id),
  CONSTRAINT livestream_comments_livestream_id_fkey FOREIGN KEY (livestream_id) REFERENCES public.livestreams(id)
);
CREATE TABLE public.livestreams (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  theater_id uuid NOT NULL,
  schedule_id uuid,
  title text NOT NULL,
  description text,
  thumbnail_url text,
  stream_url text NOT NULL,
  stream_key text,
  chat_enabled boolean DEFAULT true,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone,
  status USER-DEFINED DEFAULT 'upcoming'::stream_status,
  access_type USER-DEFINED DEFAULT 'free'::stream_access_type,
  price integer DEFAULT 0,
  current_viewers integer DEFAULT 0,
  total_views integer DEFAULT 0,
  peak_viewers integer DEFAULT 0,
  partner_name text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT livestreams_pkey PRIMARY KEY (id),
  CONSTRAINT livestreams_theater_id_fkey FOREIGN KEY (theater_id) REFERENCES public.theaters(id),
  CONSTRAINT livestreams_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.schedules(id)
);
CREATE TABLE public.masks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  character_type text,
  description text,
  image_path text NOT NULL,
  model_3d_path text,
  color_scheme ARRAY,
  symbolism text,
  tags ARRAY,
  usage_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT masks_pkey PRIMARY KEY (id)
);
CREATE TABLE public.organization_documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  type USER-DEFINED NOT NULL,
  file_url text NOT NULL,
  file_name text NOT NULL,
  file_size integer,
  mime_type text,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::document_status,
  verified_at timestamp with time zone,
  verified_by uuid,
  rejection_reason text,
  expires_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organization_documents_pkey PRIMARY KEY (id),
  CONSTRAINT organization_documents_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_documents_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.organization_members (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'staff'::member_role,
  can_create_events boolean DEFAULT false,
  can_manage_venues boolean DEFAULT false,
  can_view_financials boolean DEFAULT false,
  can_manage_members boolean DEFAULT false,
  is_active boolean DEFAULT true,
  invited_at timestamp with time zone,
  joined_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organization_members_pkey PRIMARY KEY (id),
  CONSTRAINT organization_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.organization_reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  reviewer_id uuid NOT NULL,
  previous_status USER-DEFINED,
  new_status USER-DEFINED NOT NULL,
  comment text,
  internal_note text,
  actions_taken ARRAY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organization_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT organization_reviews_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  owner_id uuid NOT NULL,
  type USER-DEFINED NOT NULL DEFAULT 'individual'::organization_type,
  legal_name text NOT NULL,
  display_name text,
  description text,
  tax_code text CHECK (tax_code IS NULL OR length(tax_code) >= 10),
  business_license_number text,
  legal_representative_name text,
  legal_representative_id text,
  email text NOT NULL CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  phone text NOT NULL CHECK (phone ~ '^\+?[0-9]{10,15}$'::text),
  address text,
  city text,
  website text,
  fanpage text,
  bank_name text,
  bank_account_number text,
  bank_account_name text,
  bank_branch text,
  logo_url text,
  cover_image_url text,
  images ARRAY DEFAULT '{}'::text[],
  status USER-DEFINED NOT NULL DEFAULT 'draft'::organization_status,
  verified_at timestamp with time zone,
  verified_by uuid,
  rejected_at timestamp with time zone,
  rejected_by uuid,
  rejection_reason text,
  admin_notes text,
  internal_notes text,
  terms_accepted_at timestamp with time zone,
  terms_version text,
  can_livestream boolean DEFAULT false,
  can_sell_tickets boolean DEFAULT false,
  max_events_per_month integer DEFAULT 5,
  max_ticket_price integer DEFAULT 1000000,
  escrow_days integer DEFAULT 7,
  commission_rate numeric DEFAULT 10.00,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  submitted_at timestamp with time zone,
  CONSTRAINT organizations_pkey PRIMARY KEY (id),
  CONSTRAINT organizations_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.profiles(id),
  CONSTRAINT organizations_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id),
  CONSTRAINT organizations_rejected_by_fkey FOREIGN KEY (rejected_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  transaction_id text NOT NULL UNIQUE,
  booking_id uuid NOT NULL,
  user_id uuid NOT NULL,
  amount integer NOT NULL,
  payment_method USER-DEFINED NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::payment_status,
  gateway_response jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  failed_at timestamp with time zone,
  transfer_content text,
  bank_account_no text,
  bank_account_name text,
  bank_code text,
  reference_number text,
  expires_at timestamp with time zone,
  qr_code_url text,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.performances (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  hall_id uuid NOT NULL,
  play_id uuid NOT NULL,
  theater_id uuid NOT NULL,
  performance_date date NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone,
  base_price integer NOT NULL DEFAULT 0 CHECK (base_price >= 0),
  vip_price integer,
  balcony_price integer,
  box_price integer,
  total_seats integer NOT NULL DEFAULT 0,
  available_seats integer NOT NULL DEFAULT 0,
  sold_seats integer DEFAULT 0,
  total_revenue integer DEFAULT 0,
  status USER-DEFINED NOT NULL DEFAULT 'scheduled'::performance_status,
  notes text,
  special_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT performances_pkey PRIMARY KEY (id),
  CONSTRAINT performances_hall_id_fkey FOREIGN KEY (hall_id) REFERENCES public.halls(id),
  CONSTRAINT performances_play_id_fkey FOREIGN KEY (play_id) REFERENCES public.plays(id),
  CONSTRAINT performances_theater_id_fkey FOREIGN KEY (theater_id) REFERENCES public.theaters(id)
);
CREATE TABLE public.plays (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  theater_id uuid NOT NULL,
  title text NOT NULL,
  original_title text,
  author text,
  director text,
  description text,
  synopsis text,
  genre USER-DEFINED NOT NULL,
  duration integer,
  language text DEFAULT 'Tiếng Việt'::text,
  min_age integer DEFAULT 0,
  actors ARRAY DEFAULT '{}'::text[],
  crew_members ARRAY DEFAULT '{}'::text[],
  poster_url text,
  trailer_url text,
  images ARRAY DEFAULT '{}'::text[],
  premiere_date date,
  tags ARRAY DEFAULT '{}'::text[],
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT plays_pkey PRIMARY KEY (id),
  CONSTRAINT plays_theater_id_fkey FOREIGN KEY (theater_id) REFERENCES public.theaters(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text,
  phone text,
  avatar_url text,
  role USER-DEFINED NOT NULL DEFAULT 'user'::user_role,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.replays (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  theater_id uuid NOT NULL,
  livestream_id uuid,
  schedule_id uuid,
  title text NOT NULL,
  description text,
  thumbnail_url text,
  video_url text NOT NULL,
  duration integer,
  access_type USER-DEFINED DEFAULT 'free'::stream_access_type,
  price integer DEFAULT 0,
  ad_count integer DEFAULT 0,
  total_views integer DEFAULT 0,
  original_date timestamp with time zone,
  partner_name text,
  tags ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT replays_pkey PRIMARY KEY (id),
  CONSTRAINT replays_theater_id_fkey FOREIGN KEY (theater_id) REFERENCES public.theaters(id),
  CONSTRAINT replays_livestream_id_fkey FOREIGN KEY (livestream_id) REFERENCES public.livestreams(id),
  CONSTRAINT replays_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.schedules(id)
);
CREATE TABLE public.schedules (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  theater_id uuid NOT NULL,
  show_id uuid NOT NULL,
  venue_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  start_datetime timestamp with time zone NOT NULL,
  end_datetime timestamp with time zone NOT NULL,
  timezone text DEFAULT 'Asia/Ho_Chi_Minh'::text,
  status USER-DEFINED DEFAULT 'scheduled'::event_status,
  ticket_url text,
  enable_booking boolean DEFAULT true,
  pricing jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT schedules_pkey PRIMARY KEY (id),
  CONSTRAINT schedules_theater_id_fkey FOREIGN KEY (theater_id) REFERENCES public.theaters(id),
  CONSTRAINT schedules_show_id_fkey FOREIGN KEY (show_id) REFERENCES public.shows(id),
  CONSTRAINT schedules_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.venues(id)
);
CREATE TABLE public.seats (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  hall_id uuid NOT NULL,
  row_number integer NOT NULL CHECK (row_number > 0),
  seat_number integer NOT NULL CHECK (seat_number > 0),
  seat_type USER-DEFINED NOT NULL DEFAULT 'standard'::seat_type,
  is_wheelchair_accessible boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT seats_pkey PRIMARY KEY (id),
  CONSTRAINT seats_hall_id_fkey FOREIGN KEY (hall_id) REFERENCES public.halls(id)
);
CREATE TABLE public.shows (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title text NOT NULL,
  description text,
  synopsis text,
  duration integer,
  thumbnail_url text,
  cover_image_url text,
  trailer_url text,
  tags ARRAY,
  characters ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT shows_pkey PRIMARY KEY (id)
);
CREATE TABLE public.theaters (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  owner_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  address text NOT NULL,
  city text NOT NULL,
  phone text,
  email text,
  website text,
  logo_url text,
  cover_image_url text,
  capacity integer DEFAULT 0,
  status USER-DEFINED DEFAULT 'pending'::theater_status,
  business_license text,
  tax_code text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  approved_at timestamp with time zone,
  approved_by uuid,
  CONSTRAINT theaters_pkey PRIMARY KEY (id),
  CONSTRAINT theaters_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.profiles(id),
  CONSTRAINT theaters_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.tickets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  performance_id uuid NOT NULL,
  seat_id uuid NOT NULL,
  user_id uuid,
  ticket_code text NOT NULL UNIQUE,
  price integer NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'available'::ticket_status,
  payment_method text,
  paid_at timestamp with time zone,
  checked_in_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tickets_pkey PRIMARY KEY (id),
  CONSTRAINT tickets_performance_id_fkey FOREIGN KEY (performance_id) REFERENCES public.performances(id),
  CONSTRAINT tickets_seat_id_fkey FOREIGN KEY (seat_id) REFERENCES public.seats(id),
  CONSTRAINT tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_photos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  image_url text NOT NULL,
  mask_id uuid,
  background_url text,
  caption text,
  is_public boolean DEFAULT false,
  views integer DEFAULT 0,
  likes integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_photos_pkey PRIMARY KEY (id),
  CONSTRAINT user_photos_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_photos_mask_id_fkey FOREIGN KEY (mask_id) REFERENCES public.masks(id)
);
CREATE TABLE public.venues (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  theater_id uuid,
  name text NOT NULL,
  address text NOT NULL,
  city text NOT NULL,
  capacity integer DEFAULT 0,
  description text,
  facilities ARRAY,
  images ARRAY,
  total_rows integer DEFAULT 10,
  seats_per_row integer DEFAULT 12,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  status USER-DEFINED NOT NULL DEFAULT 'active'::venue_status,
  CONSTRAINT venues_pkey PRIMARY KEY (id),
  CONSTRAINT venues_theater_id_fkey FOREIGN KEY (theater_id) REFERENCES public.theaters(id)
);